In [1]:
import pandas as pd
import numpy as np
# disable chained assignments
pd.options.mode.chained_assignment = None 
# dataset import
df_store = pd.read_csv('https://raw.githubusercontent.com/gdv/foundationsCS-2018/master/ex-data/project/googleplaystore.csv')
df_reviews = pd.read_csv('https://raw.githubusercontent.com/gdv/foundationsCS-2018/master/ex-data/project/googleplaystore_user_reviews.csv')
df_store.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

#    1.Convert the app sizes to a number

In [2]:
#remove invalid record
df_store=df_store.drop(df_store.index[10472])
df_store= df_store.reset_index(drop=True)

In [3]:
# convert M and k size
i=0
for n in df_store["Size"]:
    if str(df_store["Size"][i]).endswith("M"):
        df_store["Size"][i]=df_store["Size"][i][:-1]
        df_store["Size"][i]=float(df_store["Size"][i]) 
        df_store["Size"][i]=df_store["Size"][i]*10**6
    if str(df_store["Size"][i]).endswith("k"):
        df_store["Size"][i]=df_store["Size"][i][:-1]
        df_store["Size"][i]=float(df_store["Size"][i]) 
        df_store["Size"][i]=df_store["Size"][i]*10**3
    i=i+1
df_store.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,1.9e+07,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,1.4e+07,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7e+06,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,2.5e+07,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8e+06,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

#    2.Convert the number of installs to a number

In [4]:
# remove unwanted characters and transform values into number
i=0
for k in df_store["Installs"]:
    df_store["Installs"][i]=df_store["Installs"][i].replace(",","")
    df_store["Installs"][i]=df_store["Installs"][i].replace("+","")
    df_store["Installs"][i]=int(df_store["Installs"][i])
    i=i+1
df_store.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,1.9e+07,10000,Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,1.4e+07,500000,Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7e+06,5000000,Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,2.5e+07,50000000,Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8e+06,100000,Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

# 3.Transform “Varies with device” into a missing value

In [5]:
df_store=df_store.replace('Varies with device',np.nan)
df_store.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19000000.0,10000,Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14000000.0,500000,Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8700000.0,5000000,Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25000000.0,50000000,Free,0,Teen,Art & Design,"June 8, 2018",NaN,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2800000.0,100000,Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

# 4.Convert Current Ver and Android Ver into a dotted number (e.g. 4.0.3 or 4.2)

In [6]:
import re
#define a function to remove all character except for numbers and point character
def convert_number(var):
    try:
        return re.sub("[^0-9.]","",var)
               
    except:
        return np.nan

In [7]:
# apply previous function
df_store["Current Ver"]=df_store.apply(lambda x:convert_number(x["Current Ver"]),axis=1)
df_store["Android Ver"]=df_store.apply(lambda x:convert_number(x["Android Ver"]),axis=1)
df_store.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19000000.0,10000,Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14000000.0,500000,Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8700000.0,5000000,Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25000000.0,50000000,Free,0,Teen,Art & Design,"June 8, 2018",NaN,4.2
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2800000.0,100000,Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4

# 5. Remove the duplicates

In [21]:
# Keep only first value for the duplicates records recognized through name and size
df_store = df_store.drop_duplicates(subset=['App','Size'], keep='first', inplace=False)
df_store= df_store.reset_index(drop=True)
df_store.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Check_Genres,Income
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19000000.0,10000,Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3,True,0.0
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14000000.0,500000,Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3,True,0.0
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8700000.0,5000000,Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3,True,0.0
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25000000.0,50000000,Free,0,Teen,Art & Design,"June 8, 2018",NaN,4.2,True,0.0
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2800000.0,100000,Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4,True,0.0

# 6. For each category, compute the number of apps

In [9]:
# Count the Apps for each category
df_store.groupby(['Category']).size().reset_index(name='counts')

               Category  counts
0        ART_AND_DESIGN      64
1     AUTO_AND_VEHICLES      85
2                BEAUTY      53
3   BOOKS_AND_REFERENCE     222
4              BUSINESS     420
5                COMICS      56
6         COMMUNICATION     316
7                DATING     171
8             EDUCATION     119
9         ENTERTAINMENT     102
10               EVENTS      64
11               FAMILY    1836
12              FINANCE     345
13       FOOD_AND_DRINK     112
14                 GAME     963
15   HEALTH_AND_FITNESS     288
16       HOUSE_AND_HOME      74
17   LIBRARIES_AND_DEMO      84
18            LIFESTYLE     369
19  MAPS_AND_NAVIGATION     131
20              MEDICAL     400
21   NEWS_AND_MAGAZINES     254
22            PARENTING      60
23      PERSONALIZATION     376
24          PHOTOGRAPHY     283
25         PRODUCTIVITY     374
26             SHOPPING     202
27               SOCIAL     239
28               SPORTS     325
29                TOOLS     830
30     TRAVEL_AND_LOCAL     219
31        VIDEO_PLAYERS     163
32              WEATHER      79

# 7. For each category, compute the average rating

In [10]:
# Average for category
df_store.groupby(df_store['Category']).mean()['Rating']

Category
ART_AND_DESIGN         4.357377
AUTO_AND_VEHICLES      4.190411
BEAUTY                 4.278571
BOOKS_AND_REFERENCE    4.344970
BUSINESS               4.098479
COMICS                 4.181481
COMMUNICATION          4.121401
DATING                 3.970149
EDUCATION              4.364407
ENTERTAINMENT          4.135294
EVENTS                 4.435556
FAMILY                 4.180335
FINANCE                4.115563
FOOD_AND_DRINK         4.172340
GAME                   4.248362
HEALTH_AND_FITNESS     4.243033
HOUSE_AND_HOME         4.150000
LIBRARIES_AND_DEMO     4.178125
LIFESTYLE              4.093355
MAPS_AND_NAVIGATION    4.036441
MEDICAL                4.171088
NEWS_AND_MAGAZINES     4.121569
PARENTING              4.300000
PERSONALIZATION        4.332215
PHOTOGRAPHY            4.156981
PRODUCTIVITY           4.183389
SHOPPING               4.230000
SOCIAL                 4.247291
SPORTS                 4.216154
TOOLS                  4.041193
TRAVEL_AND_LOCAL       4.069519
VIDEO_PLAYERS          4.044595
WEATHER                4.243056
Name: Rating, dtype: float64

# 8. Create two dataframes: one for the genres and one bridging apps and genres. So that, for instance, the app Pixel Draw - Number Art Coloring Book appears twice in the bridging table, once for Art & Design, once for Creativity

In [11]:
#8.1 create dataframe for genres
# Create a dataframe with splitted genres
d_genres=pd.DataFrame(df_store['Genres'])
d_genres=d_genres['Genres'].str.split(';', 1, expand=True)
d_genres.head()

              0             1
0  Art & Design          None
1  Art & Design  Pretend Play
2  Art & Design          None
3  Art & Design          None
4  Art & Design    Creativity

In [12]:
#create two dataframe for the corrisponding splitted genres column
d_genres0=pd.DataFrame(d_genres[0]) #column genres 1
d_genres1=pd.DataFrame(d_genres[1]) #column genres 2

#rename the column of the two dataframe with a unique name
d_genres1.columns=['Genre']
d_genres1=d_genres1.dropna() #remove NA value
d_genres0.columns=['Genre']

#Concatenate 
d_genre_conc=pd.concat([d_genres1, d_genres0], ignore_index=True, sort=False)
d_genre_conc= d_genre_conc.reset_index(drop=True)
d_genre_conc = d_genre_conc.groupby(d_genre_conc['Genre']).sum()
d_genre_conc

Empty DataFrame
Columns: []
Index: [Action, Action & Adventure, Adventure, Arcade, Art & Design, Auto & Vehicles, Beauty, Board, Books & Reference, Brain Games, Business, Card, Casino, Casual, Comics, Communication, Creativity, Dating, Education, Educational, Entertainment, Events, Finance, Food & Drink, Health & Fitness, House & Home, Libraries & Demo, Lifestyle, Maps & Navigation, Medical, Music, Music & Audio, Music & Video, News & Magazines, Parenting, Personalization, Photography, Pretend Play, Productivity, Puzzle, Racing, Role Playing, Shopping, Simulation, Social, Sports, Strategy, Tools, Travel & Local, Trivia, Video Players & Editors, Weather, Word]

In [13]:
#8.2 create bridge dataframe
#create two dataframe with the splitted column "genres"
d_bridge=pd.DataFrame(df_store[['App','Genres']])
d_bridge[['Genre1','Genre2']]=d_bridge['Genres'].str.split(';', 1, expand=True)
d_bridge=pd.DataFrame(d_bridge[['App','Genre1','Genre2']])
d_bridge.head()

,App,Genre1,Genre2
0,Photo Editor & Candy Camera & Grid & ScrapBook,Art & Design,None
1,Coloring book moana,Art & Design,Pretend Play
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",Art & Design,None
3,Sketch - Draw & Paint,Art & Design,None
4,Pixel Draw - Number Art Coloring Book,Art & Design,Creativity

In [14]:
# create a unique dataframe concatenating the 1st dataframe and the 2nd dataframe in a sequential way
i=len(d_bridge)
i=i+1
j=0
#add a new row with the value of the second dataframe
for n in d_bridge['App']:
    d_bridge.loc[i]=[d_bridge['App'][j],d_bridge['Genre2'][j],d_bridge['Genre2'][j]]
    i=i+1
    j=j+1
d_bridge=pd.DataFrame(d_bridge[['App','Genre1']])
d_bridge=d_bridge.dropna()
d_bridge.columns=['App','Genre'] #rename columns
d_bridge= d_bridge.reset_index(drop=True)
d_bridge.head()

                                                 App         Genre
0     Photo Editor & Candy Camera & Grid & ScrapBook  Art & Design
1                                Coloring book moana  Art & Design
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  Art & Design
3                              Sketch - Draw & Paint  Art & Design
4              Pixel Draw - Number Art Coloring Book  Art & Design

In [15]:
#test with an App which has two genres
d_bridge.loc[d_bridge['App'] == 'Hair saloon - Spa salon']

                           App         Genre
9350   Hair saloon - Spa salon        Casual
10071  Hair saloon - Spa salon  Pretend Play

# 9. For each genre, create a new column of the original dataframe. The new columns must have boolean values (True if the app has a given genre)

In [16]:
df_store["Check_Genres"] = df_store["Genres"].notnull()
df_store.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Check_Genres
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19000000.0,10000,Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3,True
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14000000.0,500000,Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3,True
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8700000.0,5000000,Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3,True
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25000000.0,50000000,Free,0,Teen,Art & Design,"June 8, 2018",NaN,4.2,True
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2800000.0,100000,Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4,True

# 10. For each genre, compute the average rating. What is the genre with highest average?

In [17]:
high_rate=df_store['Rating'].groupby(df_store['Genres']).mean().nlargest(20)
high_rate=high_rate.dropna()
high_rate

Genres
Board;Pretend Play                 4.800000
Comics;Creativity                  4.800000
Health & Fitness;Education         4.700000
Adventure;Brain Games              4.600000
Puzzle;Education                   4.600000
Strategy;Action & Adventure        4.600000
Entertainment;Creativity           4.533333
Music;Music & Video                4.533333
Arcade;Pretend Play                4.500000
Racing;Pretend Play                4.500000
Strategy;Education                 4.500000
Tools;Education                    4.500000
Casual;Brain Games                 4.475000
Events                             4.435556
Education;Brain Games              4.433333
Role Playing;Action & Adventure    4.425000
Card;Brain Games                   4.400000
Entertainment;Education            4.400000
Puzzle;Creativity                  4.400000
Strategy;Creativity                4.400000
Name: Rating, dtype: float64

# 11. For each app, compute the approximate income, obtain as a product of number of installs and price.

In [18]:
#apply the function which mantains only numbers and point character
df_store["Price"]=df_store.apply(lambda x:convert_number(x["Price"]),axis=1)

In [19]:
# Calculate the approximate income as numbers of installation*price
i=0
df_store["Income"]=None
for n in df_store['App']:
    df_store["Income"][i] =int(df_store["Installs"][i])*float(df_store['Price'][i])
    i=i+1
    
df_store["Income"]=df_store["Income"].astype(float)
df_store.sort_values(by=['Income'],ascending=False)[:20]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Check_Genres,Income
1748,Minecraft,FAMILY,4.5,2376564,NaN,10000000,Paid,6.99,Everyone 10+,Arcade;Action & Adventure,"July 24, 2018",1.5.2.1,NaN,True,69900000.0
4408,I am rich,LIFESTYLE,3.8,3547,1800000.0,100000,Paid,399.99,Everyone,Lifestyle,"January 12, 2018",2.0,4.0.3,True,39999000.0
4412,I Am Rich Premium,FINANCE,4.1,1867,4700000.0,50000,Paid,399.99,Everyone,Finance,"November 12, 2017",1.6,4.0,True,19999500.0
3219,Hitman Sniper,GAME,4.6,408292,29000000.0,10000000,Paid,0.99,Mature 17+,Action,"July 12, 2018",1.7.110758,4.1,True,9900000.0
6385,Grand Theft Auto: San Andreas,GAME,4.4,348962,26000000.0,1000000,Paid,6.99,Mature 17+,Action,"March 21, 2015",1.08,3.0,True,6990000.0
2267,Facetune - For Free,PHOTOGRAPHY,4.4,49553,48000000.0,1000000,Paid,5.99,Everyone,Photography,"July 25, 2018",1.3.1,4.1,True,5990000.0
4619,Sleep as Android Unlock,LIFESTYLE,4.5,23966,872000.0,1000000,Paid,5.99,Everyone,Lifestyle,"June 27, 2018",20180608,4.0,True,5990000.0
7704,DraStic DS Emulator,GAME,4.6,87766,12000000.0,1000000,Paid,4.99,Everyone,Action,"July 19, 2016",2.5.0.3,2.3,True,4990000.0
3480,I'm Rich - Trump Edition,LIFESTYLE,3.6,275,7300000.0,10000,Paid,400.00,Everyone,Lifestyle,"May 3, 2018",1.0.1,4.1,True,4000000.0
4410,I am Rich Plus,FAMILY,4.0,856,8700000.0,10000,Paid,399.99,Everyone,Entertainment,"May 19, 2018",3.0,4.4,True,3999900.0
3476,💎 I'm rich,LIFESTYLE,3.8,718,26000000.0,10000,Paid,399.99,Everyone,Lifestyle,"March 11, 2018",1.0.0,4.4,True,3999900.0
4422,I Am Rich,FAMILY,3.6,217,4900000.0,10000,Paid,389.99,Everyone,Entertainment,"June 22, 2018",1.5,4.2,True,3899900.0
4411,I am rich VIP,LIFESTYLE,3.8,411,2600000.0,10000,Paid,299.99,Everyone,Lifestyle,"July 21, 2018",1.1.1,4.3,True,2999900.0
3285,Weather Live,WEATHER,4.5,76593,NaN,500000,Paid,5.99,Everyone,Weather,"November 21, 2017",NaN,NaN,True,2995000.0
8804,Tasker,TOOLS,4.6,43045,NaN,1000000,Paid,2.99,Everyone,Tools,"June 25, 2018",NaN,NaN,True,2990000.0
6323,Threema,COMMUNICATION,4.5,51110,NaN,1000000,Paid,2.99,Everyone,Communication,"August 3, 2018",NaN,NaN,True,2990000.0
4662,Five Nights at Freddy's,GAME,4.6,100805,50000000.0,1000000,Paid,2.99,Teen,Action,"December 2, 2014",1.85,2.3,True,2990000.0
7760,Bloons TD 5,FAMILY,4.6,190086,94000000.0,1000000,Paid,2.99,Everyone,Strategy,"July 13, 2018",3.16,2.3.3,True,2990000.0
1749,Card Wars - Adventure Time,FAMILY,4.3,129603,23000000.0,1000000,Paid,2.99,Everyone 10+,Card;Action & Adventure,"February 11, 2016",1.11.0,2.3.3,True,2990000.0
1758,Human Anatomy Atlas 2018: Complete 3D Human Body,MEDICAL,4.5,2921,25000000.0,100000,Paid,24.99,Everyone,Medical,"May 25, 2018",2018.5.47,5.0,True,2499000.0

# 12. For each app, compute its minimum and maximum Sentiment_polarity

In [20]:
#compute minimum, compute maximum
max_test=df_reviews['Sentiment_Polarity'].groupby(df_reviews['App']).max().reset_index(name='max_sent')
min_test=df_reviews['Sentiment_Polarity'].groupby(df_reviews['App']).min().reset_index(name='min_sent')
#merge togheter the two results
result = pd.merge(min_test, max_test, left_on = 'App', right_on = 'App', how = 'inner')
result[:20]

                                                  App  min_sent  max_sent
0                               10 Best Foods for You -0.800000  1.000000
1                    104 找工作 - 找工作 找打工 找兼職 履歷健檢 履歷診療室 -0.112500  0.910000
2                                                11st -1.000000  1.000000
3                          1800 Contacts - Lens Store -0.300000  0.838542
4                     1LINE – One Line with One Touch -0.825000  1.000000
5    2018Emoji Keyboard 😂 Emoticons Lite -sticker&gif -0.800000  1.000000
6                        21-Day Meditation Experience -0.265625  0.587500
7                 2Date Dating App, Love and matching -0.645833  1.000000
8                         2GIS: directory & navigator -0.375000  1.000000
9                                           2RedBeans -0.800000  1.000000
10                      2ndLine - Second Phone Number -0.781250  1.000000
11         30 Day Fitness Challenge - Workout at Home -0.500000  0.900000
12                            365Scores - Live Scores  0.000000  1.000000
13                 3D Blue Glass Water Keyboard Theme       NaN       NaN
14    3D Color Pixel by Number - Sandbox Art Coloring       NaN       NaN
15                         3D Live Neon Weed Launcher  0.136364  1.000000
16                                         4 in a Row -0.800000  1.000000
17             4K Wallpapers and Ultra HD Backgrounds -0.700000  0.750000
18  591房屋交易-租屋、中古屋、新建案、實價登錄、別墅透天、公寓套房、捷運、買房賣房行情、房價... -0.300000  0.700000
19                                         591房屋交易-香港 -0.077083  0.700000